name: New data
description: Suggest a new data to add to the timeline
labels: ["new data"]
body:
  - type: input
    id: title
    attributes:
      label: Title
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: Date
      placeholder: YYYY-MM-DD
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: supports markdown
      render: markdown

  - type: textarea
    id: media
    attributes:
      label: Media
      description: Link to images, videos, websites, etc.
